modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"

[[mixins]]
config = "crooked_crooks.mixins.json"

[[mixins]]
config = "crooked_crooks_norge.mixins.json"

[[mods]]
modId = "crooked_crooks"
version = "${version}"
displayName = "Crooked Crooks"
logoFile = "icon.png"
authors = "Ennui Langeweile and Up"
description = """
Adds its own take on crooks. They multiply drops from leaves and grass, herd sheep and pull mobs!
"""

[[dependencies.crooked_crooks]]
modId = "neoforge"
type = "required"
versionRange = "[21.4.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.crooked_crooks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.22)"
ordering = "NONE"
side = "CLIENT"

[mc-publish]
modrinth = "DG76dVRB"
curseforge = "393714"
loaders = [ "neoforge" ]
